### ISSUE TITLE
“SOLID Principles in Ruby” blog post errata

### ISSUE THREAD

**Issue by vis-kid** [subvisual/blog.subvisual.co#98]
Really enjoyed the article and how it conveyed SOLID in only a couple of short paragraphs. @zamith 

Couple of minor things that caught my attention. Marked ideas for corrections in bold. It’s all in chronological order:

That's why, as **with** many things in the software area, you should use these principles as guidelines, not rules. One of the most well known sets of OO design principles is known by an acronym, SOLID. It stands for:

Let's take a look at each of them individually, and how you can use them to increase your code's quality in **Ruby**.

Probably the most well known principle, and one that **you** should try to adhere to most of the time.

The AuthenticatesUser class is responsible for authenticating the user as well as knowing if the email and password match the ones in the database. It has two responsibilities, and according to the principle it should only have one. **Let’s extract one:**

I've used a refactoring technique called Extract Class and then **used** it on the **original class** I already had**. This** is called sharing behaviour through composition.

Thus I have extended the functionality without modifying the code. In this example, I have used a technique called Dependency Injection, but many **others could** apply.

This principle applies only to inheritance, so let's **look at** an example of inheritance that breaks it:

So, they must have the same interface. Since **Ruby** does not have abstract methods, we can do it like so:

We can solve it the exact same way **we** solved it on the OCP problem, with dependency injection:

I've covered (slightly touched) five principles that when followed will almost **guaranteed** improve the quality of your code**. There** are many other**s** though, and sometimes it makes more sense to break a principle than to follow it.

Hope this was helpful and not coming off as pedantic or anything. A PR would have been a bit more smooth for both of us I guess :)

Cheers!

**Comment by zamith** [comment]
Thanks for taking the time to do this.

I've incorporated most of the comments, so I'm closing the issue.

**Comment by vis-kid** [comment]
Sure, anytime! :)

-- on the go --
